name: extension_test
description: "Testing eval and Lua for plugins"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent.git
  flutter_archive: ^6.0.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  flutter_eval: ^0.7.6
  dart_eval: ^0.7.10

dependency_overrides:
  flutter_eval:
    git:
      url: https://github.com/Zverik/flutter_eval.git
      ref: flutter_3_27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
